version: "3.9"
services:
  reactnative:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "8081:8081"
    stdin_open: true
    tty: true
    command: >
      sh -c "npm install &&
             npx react-native start"